---
- hosts: servers
  tasks:
          - name: install nodejs and npm
            apt:
                    name: ['nodejs', 'npm']
                    state: present
                    update_cache: yes

          - name: "Install forever (to run Node.js app)."
            npm: 
                    name: forever 
                    global: yes 
                    state: present

          - name: "Check list of Node.js apps running."
            command: forever list
            register: forever_list
            changed_when: false

          - name: "Start example Node.js app."
            command: forever start /vagrant/app.js
            when: "forever_list.stdout.find('/vagrant/app.js') == -1"
...
